# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/conf/options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/conf/options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16src/conf/options.proto\")\n\x13\x46\x61\x63\x65\x44\x65tectorOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\tb\x06proto3')
)




_FACEDETECTOROPTIONS = _descriptor.Descriptor(
  name='FaceDetectorOptions',
  full_name='FaceDetectorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker_uri', full_name='FaceDetectorOptions.broker_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['FaceDetectorOptions'] = _FACEDETECTOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaceDetectorOptions = _reflection.GeneratedProtocolMessageType('FaceDetectorOptions', (_message.Message,), dict(
  DESCRIPTOR = _FACEDETECTOROPTIONS,
  __module__ = 'src.conf.options_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetectorOptions)
  ))
_sym_db.RegisterMessage(FaceDetectorOptions)


# @@protoc_insertion_point(module_scope)
