# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='options.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\roptions.proto\x1a\x1cgoogle/protobuf/struct.proto\"_\n\x13\x46\x61\x63\x65\x44\x65tectorOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\t\x12\x12\n\nzipkin_uri\x18\x02 \x01(\t\x12 \n\x05model\x18\x05 \x01(\x0b\x32\x11.HaarCascadeModel\"\x81\x01\n\x10HaarCascadeModel\x12\x12\n\nmodel_file\x18\x01 \x01(\t\x12\x14\n\x0cscale_factor\x18\x02 \x01(\x02\x12\x15\n\rmin_neighbors\x18\x03 \x01(\r\x12,\n\x08min_size\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.ListValueb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_FACEDETECTOROPTIONS = _descriptor.Descriptor(
  name='FaceDetectorOptions',
  full_name='FaceDetectorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='broker_uri', full_name='FaceDetectorOptions.broker_uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zipkin_uri', full_name='FaceDetectorOptions.zipkin_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='FaceDetectorOptions.model', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=142,
)


_HAARCASCADEMODEL = _descriptor.Descriptor(
  name='HaarCascadeModel',
  full_name='HaarCascadeModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_file', full_name='HaarCascadeModel.model_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scale_factor', full_name='HaarCascadeModel.scale_factor', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_neighbors', full_name='HaarCascadeModel.min_neighbors', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_size', full_name='HaarCascadeModel.min_size', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=274,
)

_FACEDETECTOROPTIONS.fields_by_name['model'].message_type = _HAARCASCADEMODEL
_HAARCASCADEMODEL.fields_by_name['min_size'].message_type = google_dot_protobuf_dot_struct__pb2._LISTVALUE
DESCRIPTOR.message_types_by_name['FaceDetectorOptions'] = _FACEDETECTOROPTIONS
DESCRIPTOR.message_types_by_name['HaarCascadeModel'] = _HAARCASCADEMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaceDetectorOptions = _reflection.GeneratedProtocolMessageType('FaceDetectorOptions', (_message.Message,), dict(
  DESCRIPTOR = _FACEDETECTOROPTIONS,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetectorOptions)
  ))
_sym_db.RegisterMessage(FaceDetectorOptions)

HaarCascadeModel = _reflection.GeneratedProtocolMessageType('HaarCascadeModel', (_message.Message,), dict(
  DESCRIPTOR = _HAARCASCADEMODEL,
  __module__ = 'options_pb2'
  # @@protoc_insertion_point(class_scope:HaarCascadeModel)
  ))
_sym_db.RegisterMessage(HaarCascadeModel)


# @@protoc_insertion_point(module_scope)
