FROM python:3.6-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget libsm6 libxext6 libxrender-dev libglib2.0-0

WORKDIR /tmp
ADD . /tmp/
RUN pip install --user -e .
RUN rm -rf /tmp/*


