apiVersion: v1
kind: ConfigMap
metadata:
  name: face-detector
  namespace: default
data:
  detector: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 9411,
      "model": {
        "model_file": "./haarcascade_frontalface_default.xml",
        "scale_factor" : 1.1,
        "min_neighbors" : 5,  
        "min_size": [1,1]
      }
    }