apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: "is-face-detector"
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: detector
    spec:
      containers:
      - name: service
        image: luizcarloscf/is-face-detector:0.0.1
        command: ["is-face-detector"]
        args: ["/conf/options.json"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "2"
            memory: 1024Mi
        volumeMounts:
          - name: options
            mountPath: /conf/
      volumes:
      - name: options
        configMap:
          name: face-detector
          items:
          - key: detector
            path: options.json
