apiVersion: v1
kind: ConfigMap
metadata:
  name: face-detector
  namespace: default
data:
  detector: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_uri": "http://zipkin.default:9411",
      "model": {
        "path": "/opt/is-face-detector/etc/model/face_detection_yunet_2023mar.onnx",
        "conf_threshold": 0.8,
        "nms_threshold": 0.3,
        "top_k": 5000,
        "gpu": true,
        "f16": false
      }
    }
---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: is-face-detector
  namespace: default
spec:
  selector:
    matchLabels:
      app: is-face-detector
  replicas: 2
  template:
    metadata:
      labels:
        app: is-face-detector
    spec:
      containers:
      - name: is-face-detector
        image: labvisio/is-face-detector:0.0.2
        command: ["is-face-detector-stream"]
        args: ["/conf/options.json"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 2048Mi
            nvidia.com/gpu: 1
        volumeMounts:
          - name: options
            mountPath: /conf/
      volumes:
      - name: options
        configMap:
          name: face-detector
          items:
          - key: detector
            path: options.json
